name: Update README with new Pokémon

on:
  schedule:
    - cron: '0 0 * * *' # Esto se ejecuta todos los días a la medianoche UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Pokémon Image URL
        run: |
          # Generar un número aleatorio entre 1 y 1025
          POKEMON_NUMBER=$(shuf -i 1-1025 -n 1)
          # Actualizar la URL de la imagen del Pokémon en el README.md
          sed -i "s|<img src=\"[^\"]*\" alt=\".*\" id=\"pokemondehoy\"/>|<img src=\"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${POKEMON_NUMBER}.png\" alt=\"Pokémon del día\" id=\"pokemondehoy\" />|g" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update Pokémon image URL in README with new Pokémon"
          git push